### ISSUE TITLE
Virker ikke på mac med Kyngchaos installationen

### ISSUE THREAD

**Issue by AsgerPetersen** [Kortforsyningen/Qgis_plugin_Kortforsyningen_v3#20]
Pluginet fungerer ikke på mac, hvis man bruger Kyngchaos-installationen. For nuværende (QGIS 3.6) er den stadig default-installationen.

Pluginet smider følgende fejl:
```
Kunne ikke hente plugin 'Kortforsyningen' pga.  fejl ved kald til dens classFactory() metode 

TypeError: 'QVariant' object is not subscriptable 

Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/pihl/Library/Application Support/QGIS/QGIS3/profiles/Pihl/python/plugins/Kortforsyningen/__init__.py", line 35, in classFactory
    return Kortforsyningen(iface)
  File "/Users/pihl/Library/Application Support/QGIS/QGIS3/profiles/Pihl/python/plugins/Kortforsyningen/kortforsyningen.py", line 78, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

Python-version: 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
QGIS-version: 3.4.8-Madeira Madeira, exported 

Pythonsti:

/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/pihl/Library/Application Support/QGIS/QGIS3/profiles/Pihl/python
/Users/pihl/Library/Application Support/QGIS/QGIS3/profiles/Pihl/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/E/Python/3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/pihl/Library/Application Support/QGIS/QGIS3/profiles/Pihl/python
```

**Comment by AsgerPetersen** [comment]
Det ser ud til at være beslægtet med [denne bugfix](https://github.com/Septima/qgis-geosearch/commit/2e8485124e6fe02e6b8c57c55a3b0acfe72493de) i GeoSearch.

**Comment by AsgerPetersen** [comment]
Måske er dette i virkeligheden samme issue som #13.
